project:
  type: website
  output-dir: docs

website:
<<<<<<< Updated upstream
  title: "Emma and Lara's Website"
=======
  title: "Emma and Lara"
>>>>>>> Stashed changes
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - new_tab.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



